version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started 
      - dotnet restore .\CoreWebApp\WebApp\WebApp.csproj
  build:
    commands:
      - echo Build started  
      - dotnet publish -c release 
